"""Golden contract tests verifying 100% JSON schema and wire protocol compatibility with browser extension."""

import json

import pytest
from httpx import AsyncClient


@pytest.mark.asyncio
async def test_golden_contract_error_envelope_format(async_client: AsyncClient):
    resp = await async_client.get("/api/v1/non-existent-route")
    assert resp.status_code == 404
    data = resp.json()
    # Must have exact keys: success, error, requestId
    assert set(data.keys()) == {"success", "error", "requestId"}
    assert data["success"] is False
    assert set(data["error"].keys()) == {"code", "message"}
    assert data["error"]["code"] == "NOT_FOUND"
    assert "requestId" in data


@pytest.mark.asyncio
async def test_golden_contract_video_analyze_response_camelcase(async_client: AsyncClient):
    valid_id = "gold1234567"
    resp = await async_client.post("/api/v1/videos", json={"videoId": valid_id})
    assert resp.status_code == 202
    data = resp.json()

    assert data["success"] is True
    assert "video" in data
    assert data["video"]["videoId"] == valid_id
    assert "status" in data["video"]
    assert "retrievalStatus" in data
    assert "requestId" in data

    if "transcript" in data:
        summary = data["transcript"]
        assert "videoId" in summary
        assert "language" in summary
        assert "languageCode" in summary
        assert "isAutoGenerated" in summary
        assert "segmentCount" in summary
        assert "totalDuration" in summary


@pytest.mark.asyncio
async def test_golden_contract_conversation_and_messages_camelcase(async_client: AsyncClient):
    valid_id = "goldConv123"
    await async_client.post("/api/v1/videos", json={"videoId": valid_id})
    from src.services.transcript.service import TranscriptService

    await TranscriptService.get_instance().process_video_sync(valid_id)

    # Create conversation
    create_resp = await async_client.post(f"/api/v1/videos/{valid_id}/conversations")
    assert create_resp.status_code == 201
    conv = create_resp.json()["conversation"]

    # Verify camelCase keys in Conversation model
    required_conv_keys = {"id", "videoId", "title", "titleSource", "createdAt", "updatedAt"}
    assert required_conv_keys.issubset(set(conv.keys()))

    # Ask question in conversation
    ask_resp = await async_client.post(
        f"/api/v1/videos/{valid_id}/ask",
        json={
            "question": "What is covered here?",
            "conversationId": conv["id"],
            "clientRequestId": "client-req-001",
        },
    )
    assert ask_resp.status_code == 200
    ask_data = ask_resp.json()

    assert ask_data["success"] is True
    assert ask_data["videoId"] == valid_id
    assert ask_data["conversationId"] == conv["id"]
    assert "answer" in ask_data
    assert "text" in ask_data["answer"]
    assert "grounded" in ask_data["answer"]
    assert "citations" in ask_data["answer"]

    # Check citations camelCase
    for cite in ask_data["answer"]["citations"]:
        assert "chunkId" in cite
        assert "start" in cite
        assert "end" in cite

    # Fetch conversation messages
    msg_resp = await async_client.get(f"/api/v1/conversations/{conv['id']}/messages")
    assert msg_resp.status_code == 200
    msg_data = msg_resp.json()
    assert msg_data["success"] is True
    assert "messages" in msg_data

    for msg in msg_data["messages"]:
        assert "id" in msg
        assert "conversationId" in msg
        assert "role" in msg
        assert "content" in msg
        assert "createdAt" in msg


@pytest.mark.asyncio
async def test_golden_contract_streaming_sse_format(async_client: AsyncClient):
    valid_id = "goldStream1"
    await async_client.post("/api/v1/videos", json={"videoId": valid_id})
    from src.services.transcript.service import TranscriptService

    await TranscriptService.get_instance().process_video_sync(valid_id)

    resp = await async_client.post(
        f"/api/v1/videos/{valid_id}/ask?stream=true",
        json={"question": "Summarize briefly."},
    )
    assert resp.status_code == 200
    assert "text/event-stream" in resp.headers["content-type"]

    lines = resp.text.split("\n")
    events = []
    current_event = {}

    for line in lines:
        if line.startswith("event:"):
            current_event["type"] = line[6:].strip()
        elif line.startswith("data:"):
            current_event["data"] = json.loads(line[5:].strip())
        elif line == "" and "type" in current_event:
            events.append(current_event)
            current_event = {}

    # Verify event types and schema
    start_events = [e for e in events if e.get("type") == "start"]
    token_events = [e for e in events if e.get("type") == "token"]
    done_events = [e for e in events if e.get("type") == "done"]

    assert len(start_events) == 1
    assert "requestId" in start_events[0]["data"]
    assert "messageId" in start_events[0]["data"]

    assert len(token_events) >= 1
    assert "text" in token_events[0]["data"]

    assert len(done_events) == 1
    assert "message" in done_events[0]["data"]
    assert done_events[0]["data"]["message"]["role"] == "assistant"
