/**
 * Supported video processing lifecycle states.
 * Designed for forward-compatibility with future processing pipelines.
 */
export type VideoProcessingStatus =
  "accepted" | "processing" | "ready" | "unavailable" | "error";

/**
 * Request payload to register or initiate analysis for a YouTube video.
 */
export interface VideoAnalyzeRequest {
  videoId: string;
}

/**
 * A normalized, timestamped segment of the transcript.
 * Preserves timing in seconds for citation seeking and future RAG indexing.
 */
export interface TranscriptSegment {
  index: number;
  start: number;
  duration: number;
  end: number;
  text: string;
}

/**
 * Lightweight summary of transcript metadata included in status responses.
 * Avoids returning hundreds of segments during status polling.
 */
export interface TranscriptSummary {
  language: string;
  languageCode: string;
  isAutoGenerated: boolean;
  segmentCount: number;
  duration: number;
}

/**
 * Full normalized transcript domain model.
 */
export interface Transcript {
  videoId: string;
  language: string;
  languageCode: string;
  isAutoGenerated: boolean;
  segments: TranscriptSegment[];
  totalDuration: number;
}

import type { RetrievalStatus } from "./retrieval";

/**
 * Successful response returned upon video registration.
 */
export interface VideoAnalyzeResponse {
  success: true;
  video: {
    videoId: string;
    status: VideoProcessingStatus;
  };
  transcript?: TranscriptSummary;
  retrievalStatus?: RetrievalStatus;
  requestId: string;
}

/**
 * Response returned when querying current video processing status.
 */
export interface VideoStatusResponse {
  success: true;
  video: {
    videoId: string;
    status: VideoProcessingStatus;
  };
  transcript?: TranscriptSummary;
  retrievalStatus?: RetrievalStatus;
  requestId: string;
}
