import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { ApiClient, ApiClientError } from "../services/api";

describe("ApiClient Unit Tests", () => {
  const TEST_BASE_URL = "http://localhost:8787";
  let client: ApiClient;

  beforeEach(() => {
    client = new ApiClient(TEST_BASE_URL, 1000);
    vi.restoreAllMocks();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  describe("Successful Requests", () => {
    it("handles 200 OK health check response", async () => {
      const mockResponse = {
        status: "ok",
        service: "youtube-ai-api",
        version: "0.1.0",
      };

      vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(
        new Response(JSON.stringify(mockResponse), {
          status: 200,
          headers: {
            "Content-Type": "application/json",
            "X-Request-ID": "req-12345",
          },
        }),
      );

      const data = await client.health();
      expect(data).toEqual(mockResponse);
    });

    it("handles 202 Accepted registerVideo response", async () => {
      const mockResponse = {
        success: true,
        video: {
          videoId: "Gfr50f6ZBvo",
          status: "accepted",
        },
        requestId: "server-req-id-789",
      };

      vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(
        new Response(JSON.stringify(mockResponse), {
          status: 202,
          headers: {
            "Content-Type": "application/json",
            "X-Request-ID": "server-req-id-789",
          },
        }),
      );

      const res = await client.registerVideo({ videoId: "Gfr50f6ZBvo" });
      expect(res.success).toBe(true);
      expect(res.video.videoId).toBe("Gfr50f6ZBvo");
      expect(res.video.status).toBe("accepted");
      expect(res.requestId).toBe("server-req-id-789");
    });

    it("handles 200 OK getVideoStatus response", async () => {
      const mockResponse = {
        success: true,
        video: {
          videoId: "Gfr50f6ZBvo",
          status: "accepted",
        },
        requestId: "server-req-id-101",
      };

      vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(
        new Response(JSON.stringify(mockResponse), {
          status: 200,
          headers: { "Content-Type": "application/json" },
        }),
      );

      const res = await client.getVideoStatus("Gfr50f6ZBvo");
      expect(res.success).toBe(true);
      expect(res.video.videoId).toBe("Gfr50f6ZBvo");
    });

    it("handles 200 OK getTranscript response", async () => {
      const mockResponse = {
        success: true,
        videoId: "Gfr50f6ZBvo",
        transcript: {
          videoId: "Gfr50f6ZBvo",
          language: "English",
          languageCode: "en",
          isAutoGenerated: false,
          totalDuration: 60,
          segments: [
            {
              index: 0,
              start: 0,
              duration: 60,
              end: 60,
              text: "Hello world.",
            },
          ],
        },
        requestId: "server-req-id-202",
      };

      vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(
        new Response(JSON.stringify(mockResponse), {
          status: 200,
          headers: { "Content-Type": "application/json" },
        }),
      );

      const res = await client.getTranscript("Gfr50f6ZBvo");
      expect(res.success).toBe(true);
      expect(res.transcript.segments).toHaveLength(1);
      expect(res.transcript.segments[0]?.text).toBe("Hello world.");
    });

    it("handles 200 OK searchRetrieval response", async () => {
      const mockResponse = {
        success: true,
        videoId: "Gfr50f6ZBvo",
        results: [
          {
            chunk: {
              id: "chunk_Gfr50f6ZBvo_0_1234",
              videoId: "Gfr50f6ZBvo",
              chunkIndex: 0,
              text: "Neural network backpropagation.",
              start: 0,
              end: 15,
              segmentStartIndex: 0,
              segmentEndIndex: 1,
              tokenCount: 4,
            },
            score: 0.95,
          },
        ],
        requestId: "server-req-id-retrieval",
      };

      vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(
        new Response(JSON.stringify(mockResponse), {
          status: 200,
          headers: {
            "Content-Type": "application/json",
            "X-Request-ID": "server-req-id-retrieval",
          },
        }),
      );

      const res = await client.searchRetrieval("Gfr50f6ZBvo", "neural networks", 1);
      expect(res.success).toBe(true);
      expect(res.results).toHaveLength(1);
      expect(res.results[0]?.chunk.text).toBe("Neural network backpropagation.");
      expect(res.results[0]?.score).toBe(0.95);
    });
  });

  describe("Error Handling", () => {
    it("parses 4xx structured errors and throws ApiClientError", async () => {
      const errorBody = {
        success: false,
        error: {
          code: "INVALID_VIDEO_ID",
          message: "The supplied YouTube video ID is invalid.",
        },
        requestId: "err-req-400",
      };

      vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(
        new Response(JSON.stringify(errorBody), {
          status: 400,
          headers: { "Content-Type": "application/json" },
        }),
      );

      try {
        await client.registerVideo({ videoId: "invalid_id" });
        expect.unreachable("Should have thrown ApiClientError");
      } catch (err) {
        expect(err).toBeInstanceOf(ApiClientError);
        const apiErr = err as ApiClientError;
        expect(apiErr.code).toBe("INVALID_VIDEO_ID");
        expect(apiErr.statusCode).toBe(400);
      }
    });

    it("handles non-JSON 500 error responses gracefully", async () => {
      vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(
        new Response("<html>500 Internal Server Error</html>", {
          status: 500,
          statusText: "Internal Server Error",
          headers: { "Content-Type": "text/html" },
        }),
      );

      try {
        await client.health();
        expect.unreachable("Should have thrown ApiClientError");
      } catch (err) {
        expect(err).toBeInstanceOf(ApiClientError);
        const apiErr = err as ApiClientError;
        expect(apiErr.statusCode).toBe(500);
        expect(apiErr.code).toBe("HTTP_500");
      }
    });

    it("handles malformed JSON body in 200 response without crashing", async () => {
      vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(
        new Response("corrupted-not-json", {
          status: 200,
          headers: { "Content-Type": "application/json" },
        }),
      );

      await expect(client.health()).rejects.toThrow(ApiClientError);
    });

    it("handles network failure and returns descriptive error", async () => {
      vi.spyOn(globalThis, "fetch").mockRejectedValue(new TypeError("Failed to fetch"));

      try {
        await client.registerVideo({ videoId: "Gfr50f6ZBvo" });
        expect.unreachable("Should have thrown ApiClientError");
      } catch (err) {
        expect(err).toBeInstanceOf(ApiClientError);
        const apiErr = err as ApiClientError;
        expect(apiErr.code).toBe("NETWORK_ERROR");
        expect(apiErr.userMessage).toContain("Cannot connect to the server");
      }
    });

    it("handles AbortController cancellation", async () => {
      const controller = new AbortController();
      controller.abort();

      await expect(
        client.registerVideo({ videoId: "Gfr50f6ZBvo" }, controller.signal),
      ).rejects.toThrow(ApiClientError);
    });

    it("attaches X-Session-ID header to outgoing requests", async () => {
      const fetchSpy = vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(
        new Response(JSON.stringify({ status: "ok", service: "api", version: "0.1.0" }), {
          status: 200,
          headers: { "Content-Type": "application/json" },
        }),
      );

      await client.health();
      expect(fetchSpy).toHaveBeenCalledOnce();
      const callArgs = fetchSpy.mock.calls[0];
      expect(callArgs).toBeDefined();
      const init = callArgs?.[1] as { headers?: Record<string, string> } | undefined;
      const headers = init?.headers;
      expect(headers).toBeDefined();
      expect(headers?.["X-Session-ID"]).toBeDefined();
      expect(headers?.["X-Session-ID"]?.length).toBeGreaterThan(0);
    });

    it("formats user-friendly message for QUOTA_EXCEEDED", async () => {
      vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(
        new Response(
          JSON.stringify({
            success: false,
            error: {
              code: "QUOTA_EXCEEDED",
              message: "Daily question limit of 30 exceeded",
            },
            requestId: "req-quota-123",
          }),
          {
            status: 429,
            headers: { "Content-Type": "application/json" },
          },
        ),
      );

      try {
        await client.registerVideo({ videoId: "Gfr50f6ZBvo" });
        expect.unreachable("Should have thrown ApiClientError");
      } catch (err) {
        expect(err).toBeInstanceOf(ApiClientError);
        const apiErr = err as ApiClientError;
        expect(apiErr.code).toBe("QUOTA_EXCEEDED");
        expect(apiErr.statusCode).toBe(429);
        expect(apiErr.userMessage).toContain("Daily usage limit reached");
      }
    });
  });
});
