"""Normalization and segment merging constants."""

MAX_SEGMENT_DURATION = 15.0
MAX_SEGMENT_CHARACTERS = 250
MERGE_GAP_SECONDS = 1.5
MAX_TRANSCRIPT_CHARACTERS = 500_000
MAX_SEGMENTS_COUNT = 10_000
DEFAULT_PREFERRED_LANGUAGES = ["en", "en-US", "en-GB"]
