"""Constants for generation and prompt orchestration."""

from src.core.constants import (
    DEFAULT_MAX_OUTPUT_TOKENS,
    DEFAULT_PROVIDER_TIMEOUT_MS,
    DEFAULT_TEMPERATURE,
    MAX_CONTEXT_CHARACTERS,
    MAX_CONTEXT_CHUNKS,
    MAX_QUESTION_LENGTH,
    MIN_SIMILARITY_THRESHOLD,
    NO_EVIDENCE_ANSWER_TEXT,
)

MAX_STREAMED_OUTPUT_CHARS = 16000

__all__ = [
    "DEFAULT_MAX_OUTPUT_TOKENS",
    "DEFAULT_PROVIDER_TIMEOUT_MS",
    "DEFAULT_TEMPERATURE",
    "MAX_CONTEXT_CHARACTERS",
    "MAX_CONTEXT_CHUNKS",
    "MAX_QUESTION_LENGTH",
    "MIN_SIMILARITY_THRESHOLD",
    "NO_EVIDENCE_ANSWER_TEXT",
    "MAX_STREAMED_OUTPUT_CHARS",
]
